version: '3.1'

services:
  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./scripts/init.pgsql:/docker-entrypoint.d/init.sql
  app:
    image: umaac-app
    hostname: umaac-app
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db

  db-admin:
    image: dpage/pgadmin4
    hostname: db-admin
    restart: always
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@umaac.com
      PGADMIN_DEFAULT_PASSWORD: dev